[package]
name = "nuki"
version = "0.6.3"
authors = [
    "Serhii Plyhun <snuk188@gmail.com>",
    "Varphone Wong <varphone@qq.com>",
]
keywords = ["ui", "widgets", "gui", "interface", "graphics"]
description = "Rust wrapper for Nuklear 2D GUI library (https://github.com/Immediate-Mode-UI/Nuklear)"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/varphone/nuklear-rs.git"
homepage = "https://github.com/varphone/nuklear-rs"
edition = "2018"

[dependencies]
log = "~0.3"

[features]
default = []
rust_allocator = []

[dependencies.nuki-sys]
path = "nuki-sys"
version = "~4.1"
